spring:
  application:
    name: ToDoListBackend
  datasource:
    url: jdbc:postgresql://ep-blue-cherry-aq7u8gm4-pooler.c-8.us-east-1.aws.neon.tech/orders?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_hxusF3im5EfN
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
