spring:
  application:
    name: ToDoListBackend
  datasource:
    url: ${DATABASEURL}
    username: ${DATABASEUSERNAME}
    password: ${DATABASEPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
